### ISSUE TITLE
empty option in select

### ISSUE THREAD

**Issue by groetzner-net** [christianbarkowsky/contao-protectedselect#13]
Hello,
I'm using contao 4.9 but there is only one `<option value="">-</option>` listed in BE and FE.
contao-protectedselect v1.1.8
Cache is cleared.
The following entry is in the DB: 
`a:2:{i:0;a:4:{s:9:"reference";s:5:"test1";s:5:"value";s:1:"1";s:5:"label";s:1:"1";s:7:"default";s:1:"1";}i:1;a:3:{s:9:"reference";s:5:"test2";s:5:"value";s:1:"2";s:5:"label";s:1:"2";}}`
What can I do?

**Comment by christianbarkowsky** [comment]
Hey ho. I just tested it with an Contao 4.9 installation. I can't find any problem.

**Comment by groetzner-net** [comment]
Without the _contao-themes-net/odd-theme-bundle_ it is working. 
There is any conflict between contao-themes-net/odd-theme-bundle and _christianbarkowsky/contao-protectedselect_

**Comment by BennyK80** [comment]
Same problem with _contao-bootstrap/bundle_ installed. (or its dependencies)

**Comment by Philipp1978** [comment]
Hi. I have the same issue with Contao 4.4.49. Non of the above enhancements are installed. What can I contribute in order to make this issue more transparent for you?

One more remark: when I first insert a "select menu" and add some options there, Contao will display these options in the frontend even if I switch from "select menu" to "protected select menu". So, Contao somehow refers to the "select menu"? Maybe this is helpful?

**Comment by Philipp1978** [comment]
Hi again. We managed to work around the issue. By renaming the template file "form_select.html5" into "form_select.html5.bak" the issue disappeared. This is rather nasty and nothing more than just a first fix. Any other ideas?

**Comment by christianbarkowsky** [comment]
@groetzner-net @BennyK80 @Philipp1978 ... my extension use the contao system templates.
I think this is not a problem of my extension.
